const tokens = [
    {
        uuid: 1,
        symbol: 'btc.b',
        name: 'Bitcoin',
        icon: 'btcb.png',
        '24hVolume': '6818750000',
        price: '23270',
        '24hChange': '-0.80',
        '7DChange': '1.76',
        catagorys: ['Avalanche', 'Top Tokens', 'Stablecoins'],
    },
    {
        uuid: 2,
        symbol: 'bus.d',
        name: 'BUSD',
        icon: 'busd.png',
        '24hVolume': '324320000',
        price: '232',
        '24hChange': '80',
        '7DChange': '-19',
        catagorys: ['Top Tokens', 'Large Cap', 'Stablecoins'],
    },
    {
        uuid: 3,
        symbol: 'ETH',
        name: 'ethereum',
        icon: 'ethereum.png',
        '24hVolume': '20000',
        price: '325',
        '24hChange': '50',
        '7DChange': '45',
        catagorys: ['Top Tokens', 'Stablecoins'],
    },
    {
        uuid: 4,
        symbol: 'gmx',
        name: 'gmx',
        icon: 'gmx.jpg',
        '24hVolume': '234000',
        price: '32345',
        '24hChange': '-32',
        '7DChange': '9',
        catagorys: ['Avalanche', 'Top Tokens', 'Large Cap'],
    },
    {
        uuid: 5,
        symbol: 'lite',
        name: 'litecoin',
        icon: 'ethereum.png',
        '24hVolume': '3330',
        price: '332425',
        '24hChange': '10',
        '7DChange': '-35',
        catagorys: ['Large Cap'],
    },
    {
        uuid: 6,
        symbol: 'solo',
        name: 'solona',
        icon: 'solona.png',
        '24hVolume': '1000',
        price: '6643',
        '24hChange': '11',
        '7DChange': '25',
        catagorys: ['Large Cap', 'Defi', 'Stablecoins'],
    },
    {
        uuid: 7,
        symbol: 'steak',
        name: 'steak',
        icon: 'steak.png',
        '24hVolume': '3300',
        price: '7635',
        '24hChange': '0',
        '7DChange': '0',
        catagorys: ['Top Tokens', 'Stablecoins'],
    },
    {
        uuid: 8,
        symbol: 'terra',
        name: 'terra',
        icon: 'terra.png',
        '24hVolume': '76640',
        price: '32543',
        '24hChange': '51',
        '7DChange': '-7',
        catagorys: ['Large Cap', 'Defi'],
    },
    {
        uuid: 9,
        symbol: 'usd.c',
        name: 'usdc',
        icon: 'usdc.png',
        '24hVolume': '886454',
        price: '34',
        '24hChange': '-5',
        '7DChange': '45',
        catagorys: ['Large Cap', 'Defi'],
    },
    {
        uuid: 10,
        symbol: 'vtc',
        name: 'vector',
        icon: 'vtx.png',
        '24hVolume': '33221',
        price: '32245',
        '24hChange': '8',
        '7DChange': '32',
        catagorys: ['Stablecoins'],
    },
    {
        uuid: 11,
        symbol: 'wbtce',
        name: 'Wrapped BTC',
        icon: 'wbtce.png',
        '24hVolume': '6656744',
        price: '567',
        '24hChange': '44',
        '7DChange': '72',
        catagorys: ['Avalanche', 'Top Tokens'],
    },
    {
        uuid: 12,
        symbol: 'xava',
        name: 'xava',
        icon: 'xava.png',
        '24hVolume': '33221',
        price: '32245',
        '24hChange': '8',
        '7DChange': '32',
        catagorys: ['Avalanche'],
    },
];

export default tokens;
